import Image from 'next/image';

interface CondorLogoProps {
  size?: number;
  animate?: boolean;
  className?: string;
}

/**
 * Cóndor logo — "Moneda Cóndor": a mint coin with the Andean condor carved in
 * negative space. The cutout is transparent, so the page background shows
 * through and the mark works on both themes.
 *
 * Master asset: scripts/assets/condor-mark-master.png; the displayed PNG is
 * regenerated by scripts/generate-icons.mjs.
 *
 * Animation hook: when `animate` is true the root gets `.condor-animate`,
 * which plays the `condor-soar` keyframes defined in globals.css (gated
 * behind `prefers-reduced-motion: no-preference`).
 */
export default function CondorLogo({
  size = 96,
  animate = false,
  className = '',
}: CondorLogoProps) {
  const rootClass = [animate ? 'condor-animate' : '', className]
    .filter(Boolean)
    .join(' ');

  return (
    <Image
      src="/brand/condor-mark.png"
      alt=""
      aria-hidden="true"
      width={size}
      height={size}
      priority
      className={rootClass}
    />
  );
}
